name: Learn Urdu CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_to_ecs:
        description: "Proceed after tests and deploy to ECS (check to continue)"
        required: true
        default: false
        type: boolean

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY_URL: ${{ secrets.ECR_REPOSITORY_URL }} 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python manage.py test
      - name: Check user input
        if: github.event.inputs.deploy_to_ecs != 'true'
        run: |
          echo "You must check the 'Proceed after tests and deploy to ECS' checkbox to continue."
          exit 1

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event.inputs.deploy_to_ecs == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Log in to AWS ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL
      - name: Build and push Docker image
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            -t learn-urdu:latest \
            --push .
          docker tag learn-urdu:latest ${{ secrets.ECR_REPOSITORY_URL }}:latest
          docker push ${{ secrets.ECR_REPOSITORY_URL }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event.inputs.deploy_to_ecs == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Update ECS service 
        run: |
          aws ecs update-service --cluster learn_urdu-cluster --service learn_urdu-service --force-new-deployment --region $AWS_REGION